// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC1HemkpJTcmbAgOzAQ5FH_sVWkLlvJ4k',
    appId: '1:391214412743:web:4b99002341680aaf399fe2',
    messagingSenderId: '391214412743',
    projectId: 'doctor-phone-e1bc7',
    authDomain: 'doctor-phone-e1bc7.firebaseapp.com',
    storageBucket: 'doctor-phone-e1bc7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPT8v8HAy3mQDaeS4Og6yEd2nBa8ULprU',
    appId: '1:391214412743:android:ef993c76ff0b3359399fe2',
    messagingSenderId: '391214412743',
    projectId: 'doctor-phone-e1bc7',
    storageBucket: 'doctor-phone-e1bc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDncE_7V00AmwsVgbj0bxnnLvM5Fm7F-vg',
    appId: '1:391214412743:ios:690fac3b1c322485399fe2',
    messagingSenderId: '391214412743',
    projectId: 'doctor-phone-e1bc7',
    storageBucket: 'doctor-phone-e1bc7.firebasestorage.app',
    iosBundleId: 'com.example.adminpanel',
  );
}
